# Generated by Django 2.0.7 on 2021-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('inputs', models.CharField(default='', max_length=150)),
                ('outputs', models.CharField(default='', max_length=150)),
                ('algorithms', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
